-- Venedle: initial schema + seed for the characters table.
-- Mounted into /docker-entrypoint-initdb.d/ by compose; runs only when the
-- Postgres data volume is empty (first boot).
-- Individuals only (no bands/duos). Foreign-born figures who built their
-- careers in Venezuela are kept with their origin noted verbatim.
CREATE TABLE
  characters (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    field VARCHAR(50) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    birth_year INTEGER NOT NULL,
    state_of_origin VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    international_reach VARCHAR(30) NOT NULL,
    peak_era VARCHAR(100) NOT NULL,
    discipline_genre VARCHAR(150) NOT NULL,
    image_url TEXT,
    wiki_url TEXT,
    CONSTRAINT characters_field_check CHECK (
      field IN (
        'Político',
        'Deportista',
        'Músico',
        'Actor',
        'Comediante',
        'Periodista',
        'Presentador de TV',
        'Escritor',
        'Artista'
      )
    ),
    CONSTRAINT characters_gender_check CHECK (
      gender IN ('Masculino', 'Femenino', 'Non-binario')
    ),
    CONSTRAINT characters_status_check CHECK (status IN ('Vivo', 'Fallecido')),
    CONSTRAINT characters_international_reach_check CHECK (
      international_reach IN ('Local', 'Latinoamérica', 'Global')
    )
  );

INSERT INTO
  characters (
    name,
    field,
    gender,
    birth_year,
    state_of_origin,
    status,
    international_reach,
    peak_era,
    discipline_genre,
    image_url,
    wiki_url
  )
VALUES
  -- ---------------------------------------------------------------- políticos
  (
    'Hugo Chávez',
    'Político',
    'Masculino',
    1954,
    'Barinas',
    'Fallecido',
    'Global',
    'Década de 1990-2000',
    'Presidente / Militar',
    'https://upload.wikimedia.org/wikipedia/commons/9/95/Hugo_Ch%C3%A1vez_official_portrait_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Hugo_Ch%C3%A1vez'
  ),
  (
    'Nicolás Maduro',
    'Político',
    'Masculino',
    1962,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Presidente',
    'https://upload.wikimedia.org/wikipedia/commons/2/2e/Nicol%C3%A1s_Maduro_in_2023_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Nicolás_Maduro'
  ),
  (
    'Simón Bolívar',
    'Político',
    'Masculino',
    1783,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1810-1820',
    'Libertador',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Sim%C3%B3n_Bol%C3%ADvar._Toro_Moreno%2C_Luis._1922%2C_Legislative_Palace%2C_La_Paz.png/960px-Sim%C3%B3n_Bol%C3%ADvar._Toro_Moreno%2C_Luis._1922%2C_Legislative_Palace%2C_La_Paz.png',
    'https://es.wikipedia.org/wiki/Simón_Bolívar'
  ),
  (
    'Henrique Capriles',
    'Político',
    'Masculino',
    1972,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 2000-2010',
    'Gobernador / Candidato Presidencial',
    'https://upload.wikimedia.org/wikipedia/commons/e/e3/Henrique_Capriles_2022.jpg',
    'https://es.wikipedia.org/wiki/Henrique_Capriles'
  ),
  (
    'Leopoldo López',
    'Político',
    'Masculino',
    1971,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2000-2010',
    'Líder de la Oposición',
    'https://upload.wikimedia.org/wikipedia/commons/4/48/Leopoldo_Lopez_1.JPG',
    'https://es.wikipedia.org/wiki/Leopoldo_L%C3%B3pez'
  ),
  (
    'Juan Guaidó',
    'Político',
    'Masculino',
    1983,
    'Vargas',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Líder de la Oposición / Presidente Interino',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Juan_Guaid%C3%B3_2019_portrait.jpg/960px-Juan_Guaid%C3%B3_2019_portrait.jpg',
    'https://es.wikipedia.org/wiki/Juan_Guaidó'
  ),
  (
    'Rafael Caldera',
    'Político',
    'Masculino',
    1916,
    'Yaracuy',
    'Fallecido',
    'Latinoamérica',
    'Década de 1960-1990',
    'Presidente',
    'https://upload.wikimedia.org/wikipedia/commons/9/92/1994._Febrero%2C_7._Rafael_Caldera_en_su_segunda_presidencia.jpg',
    'https://es.wikipedia.org/wiki/Rafael_Caldera'
  ),
  (
    'Rómulo Betancourt',
    'Político',
    'Masculino',
    1908,
    'Miranda',
    'Fallecido',
    'Latinoamérica',
    'Década de 1940-1960',
    'Presidente / Fundador de AD',
    'https://upload.wikimedia.org/wikipedia/commons/d/df/Foto_oficial_R%C3%B3mulo_Betancourt_1959.jpg',
    'https://es.wikipedia.org/wiki/Rómulo_Betancourt'
  ),
  (
    'Francisco de Miranda',
    'Político',
    'Masculino',
    1750,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1780-1810',
    'Precursor / Militar',
    'https://upload.wikimedia.org/wikipedia/commons/b/b3/Francisco_de_Miranda_by_Tovar_y_Tovar.jpg',
    'https://es.wikipedia.org/wiki/Francisco_de_Miranda'
  ),
  (
    'Antonio José de Sucre',
    'Político',
    'Masculino',
    1795,
    'Sucre',
    'Fallecido',
    'Global',
    'Década de 1820',
    'Gran Mariscal de Ayacucho',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/Martin_Tovar_y_Tovar_12.JPG/500px-Martin_Tovar_y_Tovar_12.JPG',
    'https://es.wikipedia.org/wiki/Antonio_José_de_Sucre'
  ),
  (
    'Carlos Andrés Pérez',
    'Político',
    'Masculino',
    1922,
    'Táchira',
    'Fallecido',
    'Global',
    'Década de 1970-1990',
    'Presidente',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Carlos_Andr%C3%A9s_P%C3%A9rez_-_World_Economic_Forum_Annual_Meeting_1989.jpg/960px-Carlos_Andr%C3%A9s_P%C3%A9rez_-_World_Economic_Forum_Annual_Meeting_1989.jpg',
    'https://es.wikipedia.org/wiki/Carlos_Andrés_Pérez'
  ),
  (
    'Marcos Pérez Jiménez',
    'Político',
    'Masculino',
    1914,
    'Táchira',
    'Fallecido',
    'Global',
    'Década de 1950',
    'Dictador / Militar',
    'https://upload.wikimedia.org/wikipedia/commons/5/52/Foto_Ex_Dictador_Marcos_Perez_Jimenez_%281957%29.jpg',
    'https://es.wikipedia.org/wiki/Marcos_P%C3%A9rez_Jim%C3%A9nez'
  ),
  (
    'Juan Vicente Gómez',
    'Político',
    'Masculino',
    1857,
    'Táchira',
    'Fallecido',
    'Global',
    'Década de 1900-1930',
    'Dictador / Militar',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Juan_Vicente_G%C3%B3mez_por_Antonio_Herrera_Toro_%281911%29.jpg/960px-Juan_Vicente_G%C3%B3mez_por_Antonio_Herrera_Toro_%281911%29.jpg',
    'https://es.wikipedia.org/wiki/Juan_Vicente_G%C3%B3mez'
  ),
  (
    'María Corina Machado',
    'Político',
    'Femenino',
    1967,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Líder de la Oposición',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Nobel_Peace_Prize_2025_-_Mar%C3%ADa_Corina_Machado_press_conference_%283x4_cropped%29.jpg/960px-Nobel_Peace_Prize_2025_-_Mar%C3%ADa_Corina_Machado_press_conference_%283x4_cropped%29.jpg',
    'https://es.wikipedia.org/wiki/María_Corina_Machado'
  ),
  (
    'Diosdado Cabello',
    'Político',
    'Masculino',
    1963,
    'Monagas',
    'Vivo',
    'Global',
    'Década de 2000-actualidad',
    'Militar / Dirigente Político',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Diosdado_Cabello_2025.jpg/960px-Diosdado_Cabello_2025.jpg',
    'https://es.wikipedia.org/wiki/Diosdado_Cabello'
  ),
  (
    'Jóvito Villalba',
    'Político',
    'Masculino',
    1908,
    'Nueva Esparta',
    'Fallecido',
    'Latinoamérica',
    'Década de 1940-1970',
    'Fundador de URD',
    'https://upload.wikimedia.org/wikipedia/commons/e/ef/1958._Enero%2C_31._Portada_revista_Momento_%28J%C3%B3vito_Villalba%29.jpg',
    'https://es.wikipedia.org/wiki/J%C3%B3vito_Villalba'
  ),
  (
    'Andrés Eloy Blanco',
    'Político',
    'Masculino',
    1896,
    'Sucre',
    'Fallecido',
    'Global',
    'Década de 1920-1950',
    'Poeta / Político',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Andr%C3%A9s_Eloy_Blanco%2C_1941.jpg/500px-Andr%C3%A9s_Eloy_Blanco%2C_1941.jpg',
    'https://es.wikipedia.org/wiki/Andr%C3%A9s_Eloy_Blanco'
  ),
  (
    'Ezequiel Zamora',
    'Político',
    'Masculino',
    1817,
    'Miranda',
    'Fallecido',
    'Local',
    'Década de 1840-1860',
    'General del Pueblo Soberano',
    'https://upload.wikimedia.org/wikipedia/commons/b/b9/Ezequiel_Zamora_2.jpg',
    'https://es.wikipedia.org/wiki/Ezequiel_Zamora'
  ),
  (
    'Antonio Guzmán Blanco',
    'Político',
    'Masculino',
    1829,
    'Caracas',
    'Fallecido',
    'Latinoamérica',
    'Década de 1870-1880',
    'Presidente / Modernizador',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Martin_Tovar_y_Tovar_20.JPG/960px-Martin_Tovar_y_Tovar_20.JPG',
    'https://es.wikipedia.org/wiki/Antonio_Guzm%C3%A1n_Blanco'
  ),
  (
    'Rafael Urdaneta',
    'Político',
    'Masculino',
    1788,
    'Zulia',
    'Fallecido',
    'Global',
    'Década de 1810-1830',
    'Militar / Prócer',
    'https://upload.wikimedia.org/wikipedia/commons/5/5e/Rafael_urdaneta.jpg',
    'https://es.wikipedia.org/wiki/Rafael_Urdaneta'
  ),
  (
    'José Antonio Páez',
    'Político',
    'Masculino',
    1790,
    'Portuguesa',
    'Fallecido',
    'Latinoamérica',
    'Década de 1830-1850',
    'Caudillo / Presidente',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Jose_Antonio_P%C3%A1ez_restored.jpg/960px-Jose_Antonio_P%C3%A1ez_restored.jpg',
    'https://es.wikipedia.org/wiki/Jos%C3%A9_Antonio_P%C3%A1ez'
  ),
  (
    'Isaías Medina Angarita',
    'Político',
    'Masculino',
    1897,
    'Táchira',
    'Fallecido',
    'Latinoamérica',
    'Década de 1940',
    'Presidente / Militar',
    'https://upload.wikimedia.org/wikipedia/commons/8/80/Retrato_de_Isa%C3%ADas_Medina_Angarita.jpg',
    'https://es.wikipedia.org/wiki/Isa%C3%ADas_Medina_Angarita'
  ),
  -- --------------------------------------------------------------- deportistas
  (
    'Miguel Cabrera',
    'Deportista',
    'Masculino',
    1983,
    'Aragua',
    'Vivo',
    'Global',
    'Década de 2000-2010',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Miguel_Cabrera_in_2014_%2814174921525%29.jpg/960px-Miguel_Cabrera_in_2014_%2814174921525%29.jpg',
    'https://es.wikipedia.org/wiki/Miguel_Cabrera_(beisbolista)'
  ),
  (
    'Omar Vizquel',
    'Deportista',
    'Masculino',
    1967,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1990-2000',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/2/2c/Omar_Vizquel_warming_up.jpg',
    'https://es.wikipedia.org/wiki/Omar_Vizquel'
  ),
  (
    'Yulimar Rojas',
    'Deportista',
    'Femenino',
    1995,
    'Anzoátegui',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Atletismo (Salto Triple)',
    'https://upload.wikimedia.org/wikipedia/commons/5/5d/Yulimar_Rojas_-_Triple_saut_Femmes_%2848614911652%29_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Yulimar_Rojas'
  ),
  (
    'Pastor Maldonado',
    'Deportista',
    'Masculino',
    1985,
    'Zulia',
    'Vivo',
    'Global',
    'Década de 2010',
    'Fórmula 1',
    'https://upload.wikimedia.org/wikipedia/commons/0/00/Pastor_Maldonado_2015_Malaysia.jpg',
    'https://es.wikipedia.org/wiki/Pastor_Maldonado'
  ),
  (
    'Magglio Ordóñez',
    'Deportista',
    'Masculino',
    1974,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1990-2000',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/0/08/Magglio_Ord%C3%B3%C3%B1ez_2008.jpg',
    'https://es.wikipedia.org/wiki/Magglio_Ord%C3%B3%C3%B1ez'
  ),
  (
    'Johan Santana',
    'Deportista',
    'Masculino',
    1979,
    'Mérida',
    'Vivo',
    'Global',
    'Década de 2000-2010',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/6/6c/Johan_Santana_on_May_5%2C_2012.jpg',
    'https://es.wikipedia.org/wiki/Johan_Santana'
  ),
  (
    'Félix Hernández',
    'Deportista',
    'Masculino',
    1986,
    'Carabobo',
    'Vivo',
    'Global',
    'Década de 2000-2010',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/f/f2/F%C3%A9lix_Hern%C3%A1ndez_on_May_11%2C_2011.jpg',
    'https://es.wikipedia.org/wiki/F%C3%A9lix_Hern%C3%A1ndez_(beisbolista)'
  ),
  (
    'Edwin Valero',
    'Deportista',
    'Masculino',
    1981,
    'Mérida',
    'Fallecido',
    'Global',
    'Década de 2000',
    'Boxeo',
    'https://upload.wikimedia.org/wikipedia/commons/5/56/Edwin_Valero.jpg',
    'https://es.wikipedia.org/wiki/Edwin_Valero'
  ),
  (
    'Gabriela Isler',
    'Deportista',
    'Femenino',
    1988,
    'Carabobo',
    'Vivo',
    'Global',
    'Década de 2010',
    'Reinado de Belleza (Miss Universo)',
    'https://upload.wikimedia.org/wikipedia/commons/7/7f/Mar%C3%ADa_Gabriela_Isler_cropped.jpg',
    'https://es.wikipedia.org/wiki/Gabriela_Isler'
  ),
  (
    'Dayana Mendoza',
    'Deportista',
    'Femenino',
    1986,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2000',
    'Reinado de Belleza (Miss Universo)',
    'https://upload.wikimedia.org/wikipedia/commons/3/32/Miss_Universe_Dayana_Mendoza_en_Nicaragua_11.jpg',
    'https://es.wikipedia.org/wiki/Dayana_Mendoza'
  ),
  (
    'Stefanía Fernández',
    'Deportista',
    'Femenino',
    1990,
    'Mérida',
    'Vivo',
    'Global',
    'Década de 2000-2010',
    'Reinado de Belleza (Miss Universo)',
    'https://upload.wikimedia.org/wikipedia/commons/c/cf/STEFANIA2.JPG',
    'https://es.wikipedia.org/wiki/Stefan%C3%ADa_Fern%C3%A1ndez'
  ),
  (
    'Irene Sáez',
    'Deportista',
    'Femenino',
    1961,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1980-1990',
    'Reinado de Belleza (Miss Universo) / Política',
    'https://upload.wikimedia.org/wikipedia/commons/4/44/Irene_S%C3%A1ez_portrait_in_1997_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Irene_S%C3%A1ez'
  ),
  (
    'Salomón Rondón',
    'Deportista',
    'Masculino',
    1989,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Fútbol',
    'https://upload.wikimedia.org/wikipedia/commons/7/78/Salom%C3%B3n_Rond%C3%B3n_2021.jpg',
    'https://es.wikipedia.org/wiki/Salom%C3%B3n_Rond%C3%B3n'
  ),
  (
    'Josef Martínez',
    'Deportista',
    'Masculino',
    1993,
    'Carabobo',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Fútbol',
    'https://upload.wikimedia.org/wikipedia/commons/6/6b/Josef_Mart%C3%ADnez_Atlanta_United_2017.jpg',
    'https://es.wikipedia.org/wiki/Josef_Martínez'
  ),
  (
    'Juan Arango',
    'Deportista',
    'Masculino',
    1980,
    'Zulia',
    'Vivo',
    'Latinoamérica',
    'Década de 2000-2010',
    'Fútbol',
    'https://upload.wikimedia.org/wikipedia/commons/9/98/Juan_Arango_2012_Borussia_M%C3%B6nchengladbach.jpg',
    'https://es.wikipedia.org/wiki/Juan_Arango'
  ),
  (
    'Tomás Rincón',
    'Deportista',
    'Masculino',
    1988,
    'Táchira',
    'Vivo',
    'Latinoamérica',
    'Década de 2010-actualidad',
    'Fútbol',
    'https://upload.wikimedia.org/wikipedia/commons/0/0a/USAvVEN_2019-06-09_-_Tom%C3%A1s_Rinc%C3%B3n_%2851169629847%29_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Tom%C3%A1s_Rinc%C3%B3n'
  ),
  (
    'Yeferson Soteldo',
    'Deportista',
    'Masculino',
    1997,
    'Portuguesa',
    'Vivo',
    'Latinoamérica',
    'Década de 2020-actualidad',
    'Fútbol',
    'https://upload.wikimedia.org/wikipedia/commons/a/a6/Soteldo_2018_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Yeferson_Soteldo'
  ),
  (
    'Luis Aparicio',
    'Deportista',
    'Masculino',
    1934,
    'Zulia',
    'Vivo',
    'Global',
    'Década de 1950-1970',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/0/05/Luis_Aparicio%2C_70CWS.png',
    'https://es.wikipedia.org/wiki/Luis_Aparicio'
  ),
  (
    'José Altuve',
    'Deportista',
    'Masculino',
    1990,
    'Carabobo',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/0/0c/Jose_Altuve_in_Houston_in_January_2015.jpg',
    'https://es.wikipedia.org/wiki/Jos%C3%A9_Altuve'
  ),
  (
    'Ronald Acuña Jr.',
    'Deportista',
    'Masculino',
    1997,
    'Vargas',
    'Vivo',
    'Global',
    'Década de 2020-actualidad',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/a/a7/Ronald_Acuna_Jr._HR_from_Nationals_vs._Braves_at_Nationals_Park%2C_April_6th%2C_2021_%28All-Pro_Reels_Photography%29_%2851102624580%29.png',
    'https://es.wikipedia.org/wiki/Ronald_Acu%C3%B1a_Jr%2E'
  ),
  (
    'Salvador Pérez',
    'Deportista',
    'Masculino',
    1990,
    'Carabobo',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/8/84/Salvador_P%C3%A9rez_on_October_19%2C_2015.jpg',
    'https://es.wikipedia.org/wiki/Salvador_Pérez'
  ),
  (
    'Andrés Galarraga',
    'Deportista',
    'Masculino',
    1961,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1980-2000',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/b/b8/Gato96.png',
    'https://es.wikipedia.org/wiki/Andrés_Galarraga'
  ),
  (
    'Bobby Abreu',
    'Deportista',
    'Masculino',
    1974,
    'Aragua',
    'Vivo',
    'Global',
    'Década de 1990-2010',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/3/31/BobbyAbreu.jpg',
    'https://es.wikipedia.org/wiki/Bobby_Abreu'
  ),
  (
    'Dave Concepción',
    'Deportista',
    'Masculino',
    1948,
    'Miranda',
    'Vivo',
    'Global',
    'Década de 1970-1980',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/f/f7/Dave_Concepcion_-_Cincinnati_Reds.jpg',
    'https://es.wikipedia.org/wiki/Dave_Concepción'
  ),
  (
    'Oswaldo Guillén',
    'Deportista',
    'Masculino',
    1964,
    'Miranda',
    'Vivo',
    'Global',
    'Década de 1980-2000',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/2/26/Ozzie_Guillen_by_Keith_Allison.jpg',
    'https://es.wikipedia.org/wiki/Oswaldo_Guill%C3%A9n'
  ),
  (
    'César Tovar',
    'Deportista',
    'Masculino',
    1940,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1960-1970',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/3/33/Cesar_Tovar_-_Texas_Rangers_-_1974.jpg',
    'https://es.wikipedia.org/wiki/C%C3%A9sar_Tovar'
  ),
  (
    'Carlos Zambrano',
    'Deportista',
    'Masculino',
    1981,
    'Carabobo',
    'Vivo',
    'Global',
    'Década de 2000-2010',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/8/8f/Carlos_Zambrano_-_2008_-_cropped.jpg',
    'https://es.wikipedia.org/wiki/Carlos_Zambrano'
  ),
  (
    'Francisco Rodríguez',
    'Deportista',
    'Masculino',
    1982,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2000-2010',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/f/fd/Francisco_Rodr%C3%ADguez_on_August_4%2C_2013.jpg',
    'https://es.wikipedia.org/wiki/Francisco_Rodr%C3%ADguez_(beisbolista)'
  ),
  (
    'Eugenio Suárez',
    'Deportista',
    'Masculino',
    1991,
    'Bolívar',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Béisbol',
    'https://upload.wikimedia.org/wikipedia/commons/e/e9/EugenioSuarez2025.png',
    'https://es.wikipedia.org/wiki/Eugenio_Su%C3%A1rez_(beisbolista)'
  ),
  (
    'Rubén Limardo',
    'Deportista',
    'Masculino',
    1985,
    'Bolívar',
    'Vivo',
    'Global',
    'Década de 2010',
    'Esgrima',
    'https://upload.wikimedia.org/wikipedia/commons/b/be/Ruben_Limardo_%28VEN%29_2013.jpg',
    'https://es.wikipedia.org/wiki/Rub%C3%A9n_Limardo'
  ),
  (
    'Johnny Cecotto',
    'Deportista',
    'Masculino',
    1956,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1970-1980',
    'Motociclismo',
    'https://upload.wikimedia.org/wikipedia/commons/4/44/Johnny_Cecotto_%281978%29.jpg',
    'https://es.wikipedia.org/wiki/Johnny_Cecotto'
  ),
  (
    'Greivis Vásquez',
    'Deportista',
    'Masculino',
    1987,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2010',
    'Baloncesto',
    'https://upload.wikimedia.org/wikipedia/commons/3/32/Greivis_Vasquez_Hornets.jpg',
    'https://es.wikipedia.org/wiki/Greivis_Vásquez'
  ),
  (
    'Daniel Dhers',
    'Deportista',
    'Masculino',
    1985,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2000-2020',
    'BMX',
    'https://cronica.uno/wp-content/uploads/2021/08/DHERS_MEDALLA_COV.jpg',
    'https://es.wikipedia.org/wiki/Daniel_Dhers'
  ),
  -- -------------------------------------------------------------------- músicos
  (
    'José Luis Rodríguez ''El Puma''',
    'Músico',
    'Masculino',
    1943,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1970-1990',
    'Pop / Balada',
    'https://upload.wikimedia.org/wikipedia/commons/7/76/Festival_de_Las_Condes_2020_05.jpg',
    'https://es.wikipedia.org/wiki/Jos%C3%A9_Luis_Rodr%C3%ADguez_(cantante)'
  ),
  (
    'Ricardo Montaner',
    'Músico',
    'Masculino',
    1957,
    'Argentina (naturalizado venezolano)',
    'Vivo',
    'Global',
    'Década de 1980-actualidad',
    'Pop / Balada',
    'https://upload.wikimedia.org/wikipedia/commons/5/52/Ricardo_Montaner_Latin_Grammys_2021.jpg',
    'https://es.wikipedia.org/wiki/Ricardo_Montaner'
  ),
  (
    'Franco De Vita',
    'Músico',
    'Masculino',
    1954,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1980-2010',
    'Pop / Rock',
    'https://upload.wikimedia.org/wikipedia/commons/d/d4/Franco_de_Vita_en_Primera_Fila_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Franco_De_Vita'
  ),
  (
    'Carlos Baute',
    'Músico',
    'Masculino',
    1974,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2000-2010',
    'Pop / Pop Latino',
    'https://static.wikia.nocookie.net/esmusic/images/4/40/Carlos_Baute.jpg/revision/latest/scale-to-width-down/1000?cb=20171203183530',
    'https://es.wikipedia.org/wiki/Carlos_Baute'
  ),
  (
    'Oscar D''León',
    'Músico',
    'Masculino',
    1943,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1970-2000',
    'Salsa',
    'https://upload.wikimedia.org/wikipedia/commons/2/27/Oscar_D%27Le%C3%B3n_2009.jpg',
    'https://es.wikipedia.org/wiki/Oscar_D%27Le%C3%B3n'
  ),
  (
    'Luis Silva',
    'Músico',
    'Masculino',
    1969,
    'Caracas',
    'Vivo',
    'Local',
    'Década de 1990-2010',
    'Pop / Balada',
    'https://upload.wikimedia.org/wikipedia/commons/9/96/Luis_Silva.jpg',
    'https://es.wikipedia.org/wiki/Luis_Silva_(cantante)'
  ),
  (
    'Simón Díaz',
    'Músico',
    'Masculino',
    1928,
    'Aragua',
    'Fallecido',
    'Global',
    'Década de 1960-2000',
    'Folk / Llanera',
    'https://i0.wp.com/mincomercionacional.gob.ve/wp-content/uploads/2020/08/WhatsApp-Image-2020-08-08-at-8.56.29-AM.jpeg?w=700&ssl=1',
    'https://es.wikipedia.org/wiki/Sim%C3%B3n_D%C3%ADaz'
  ),
  (
    'Soledad Bravo',
    'Músico',
    'Femenino',
    1943,
    'España (naturalizada venezolana)',
    'Vivo',
    'Latinoamérica',
    'Década de 1960-1990',
    'Folk / Protesta',
    'https://upload.wikimedia.org/wikipedia/commons/b/b2/Soledad_bravo.jpg',
    'https://es.wikipedia.org/wiki/Soledad_Bravo'
  ),
  (
    'Teresa Carreño',
    'Músico',
    'Femenino',
    1853,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1860-1910',
    'Piano Clásico / Compositora',
    'https://upload.wikimedia.org/wikipedia/commons/2/2b/Teresa_Carre%C3%B1o%2C_1916.jpg',
    'https://es.wikipedia.org/wiki/Teresa_Carre%C3%B1o'
  ),
  (
    'Neutro Shorty',
    'Músico',
    'Masculino',
    1994,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2020-actualidad',
    'Trap / Rap',
    'https://lastfm-img.freetls.fastly.net/i/u/770x0/e042b3a31c19abed73c0a07b2ba523e4.jpg#e042b3a31c19abed73c0a07b2ba523e4',
    'https://es.wikipedia.org/wiki/Neutro_Shorty'
  ),
  (
    'Danny Ocean',
    'Músico',
    'Masculino',
    1992,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Pop Urbano',
    'https://lastfm-img.freetls.fastly.net/i/u/770x0/e0eba7f66ff9d3edef2077c34cf21d44.jpg#e0eba7f66ff9d3edef2077c34cf21d44',
    'https://es.wikipedia.org/wiki/Danny_Ocean'
  ),
  (
    'Big Soto',
    'Músico',
    'Masculino',
    1996,
    'Sucre',
    'Vivo',
    'Global',
    'Década de 2020-actualidad',
    'Trap / Rap',
    'https://lastfm-img.freetls.fastly.net/i/u/770x0/258047ba1fb8095b5ec3ce5605f0bb22.jpg#258047ba1fb8095b5ec3ce5605f0bb22',
    'https://es.wikipedia.org/wiki/Big_Soto'
  ),
  (
    'Nacho',
    'Músico',
    'Masculino',
    1983,
    'Anzoátegui',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'Reggaetón / Pop',
    'https://upload.wikimedia.org/wikipedia/commons/7/7f/Nacho_%28cropped%29.png',
    'https://es.wikipedia.org/wiki/Nacho_(cantante)'
  ),
  (
    'Canserbero',
    'Músico',
    'Masculino',
    1988,
    'Aragua',
    'Fallecido',
    'Global',
    'Década de 2000',
    'Rap / Hip Hop',
    'https://lastfm-img.freetls.fastly.net/i/u/770x0/f0ce8ca348318208d956b3df3c4e855d.jpg#f0ce8ca348318208d956b3df3c4e855d',
    'https://es.wikipedia.org/wiki/Canserbero'
  ),
  (
    'Gustavo Dudamel',
    'Músico',
    'Masculino',
    1981,
    'Lara',
    'Vivo',
    'Global',
    'Década de 2000-actualidad',
    'Director de Orquesta',
    'https://upload.wikimedia.org/wikipedia/commons/a/ad/Gustavo_Dudamel.jpeg',
    'https://es.wikipedia.org/wiki/Gustavo_Dudamel'
  ),
  (
    'Lil Supa',
    'Músico',
    'Masculino',
    1985,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 2000-actualidad',
    'Rap / Hip Hop',
    'https://lastfm-img.freetls.fastly.net/i/u/770x0/70a6ea4d3105df1ddcea8da8a11a4969.jpg#70a6ea4d3105df1ddcea8da8a11a4969',
    'https://es.wikipedia.org/wiki/Lil_Supa'
  ),
  (
    'Alfredo Sadel',
    'Músico',
    'Masculino',
    1930,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1940-1980',
    'Bolero / Lírico',
    'https://upload.wikimedia.org/wikipedia/commons/1/1f/Alfredo-sadel.jpg',
    'https://es.wikipedia.org/wiki/Alfredo_Sadel'
  ),
  (
    'Akapellah',
    'Músico',
    'Masculino',
    1991,
    'Maracay',
    'Vivo',
    'Global',
    'Década de 2010-Actualidad',
    'Rap / Hip Hop',
    'https://upload.wikimedia.org/wikipedia/commons/8/8f/Aldemaro_Romero.jpg',
    'https://es.wikipedia.org/wiki/Akapellah'
  ),
  (
    'Reynaldo Armas',
    'Músico',
    'Masculino',
    1953,
    'Guárico',
    'Vivo',
    'Latinoamérica',
    'Década de 1970-actualidad',
    'Música Llanera',
    'https://lastfm-img.freetls.fastly.net/i/u/770x0/280747c3594b853a632e2b28746eac78.jpg#280747c3594b853a632e2b28746eac78',
    'https://es.wikipedia.org/wiki/Reynaldo_Armas'
  ),
  (
    'Ilan Chester',
    'Músico',
    'Masculino',
    1952,
    'Israel (naturalizado venezolano)',
    'Vivo',
    'Latinoamérica',
    'Década de 1980-actualidad',
    'Pop / Balada',
    'https://lastfm-img.freetls.fastly.net/i/u/770x0/b6eba7ff10ab4b5fdc33a1fbe7906968.jpg#b6eba7ff10ab4b5fdc33a1fbe7906968',
    'https://es.wikipedia.org/wiki/Ilan_Chester'
  ),
  (
    'Gualberto Ibarreto',
    'Músico',
    'Masculino',
    1947,
    'Sucre',
    'Vivo',
    'Latinoamérica',
    'Década de 1970-actualidad',
    'Folclore / Galerón',
    'https://upload.wikimedia.org/wikipedia/commons/2/2e/Gualberto_Ibarreto_cantando.jpg',
    'https://es.wikipedia.org/wiki/Gualberto_Ibarreto'
  ),
  (
    'Cecilia Todd',
    'Músico',
    'Femenino',
    1954,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 1970-actualidad',
    'Folclore',
    'https://upload.wikimedia.org/wikipedia/commons/a/a1/Cecilia_Todd.JPG',
    'https://es.wikipedia.org/wiki/Cecilia_Todd'
  ),
  (
    'Asier Cazalis',
    'Músico',
    'Masculino',
    1972,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 2000-actualidad',
    'Rock',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD8qAaT3gpWy7RIDxaMYZ17ZwHf-eRh4oRzbc5ZXX01a6XobVCqDWJZyg&s=10',
    'https://es.wikipedia.org/wiki/Asier_Cazalis'
  ),
  -- --------------------------------------------------------------------- actores
  (
    'Edgar Ramírez',
    'Actor',
    'Masculino',
    1977,
    'Táchira',
    'Vivo',
    'Global',
    'Década de 2000-actualidad',
    'Cine / TV',
    'https://upload.wikimedia.org/wikipedia/commons/7/70/Edgar_Ramirez_at_the_2024_Toronto_International_Film_Festival_3.jpg',
    'https://es.wikipedia.org/wiki/Edgar_Ram%C3%ADrez'
  ),
  (
    'Majandra Delfino',
    'Actor',
    'Femenino',
    1981,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1990-2000',
    'TV / Cine',
    'https://upload.wikimedia.org/wikipedia/commons/4/4b/Majandra_Delfino_at_ATX_2014.jpg',
    'https://es.wikipedia.org/wiki/Majandra_Delfino'
  ),
  (
    'Jonathan Jakubowicz',
    'Actor',
    'Masculino',
    1978,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2000-actualidad',
    'Cine / Director',
    'https://upload.wikimedia.org/wikipedia/commons/7/7c/Jonathan_Jakubowicz_Cannes_2016.jpg',
    'https://es.wikipedia.org/wiki/Jonathan_Jakubowicz'
  ),
  (
    'Gaby Espino',
    'Actor',
    'Femenino',
    1977,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 2000-actualidad',
    'TV / Telenovela',
    'https://pics.filmaffinity.com/gaby_espino-101309552212784-nm_large.jpg',
    'https://es.wikipedia.org/wiki/Gaby_Espino'
  ),
  (
    'Fernando Carrillo',
    'Actor',
    'Masculino',
    1970,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 1990-2000',
    'TV / Telenovela',
    'https://static.wikia.nocookie.net/telenovela-database/images/8/8d/Fernando-carillo.jpg/revision/latest?cb=20210508005319',
    'https://es.wikipedia.org/wiki/Fernando_Carrillo_(actor)'
  ),
  (
    'Lupita Ferrer',
    'Actor',
    'Femenino',
    1947,
    'Zulia',
    'Vivo',
    'Latinoamérica',
    'Década de 1970-1990',
    'TV / Telenovela',
    'https://upload.wikimedia.org/wikipedia/commons/7/72/Yolanda_Guadalupe_Ferrer.jpg',
    'https://es.wikipedia.org/wiki/Lupita_Ferrer'
  ),
  (
    'Hilda Abrahamz',
    'Actor',
    'Femenino',
    1959,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 1980-2000',
    'TV / Telenovela',
    'https://upload.wikimedia.org/wikipedia/commons/4/4b/HILDA_ABRAHAMZ.jpg',
    'https://es.wikipedia.org/wiki/Hilda_Abrahamz'
  ),
  (
    'Mimí Lazo',
    'Actor',
    'Femenino',
    1954,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 1980-actualidad',
    'Teatro / TV / Cine',
    'https://m.media-amazon.com/images/M/MV5BYTQ4ZTkwMGItNGJhNy00ZmYxLWI3YjktZmY2ZTY1NTYzODZiXkEyXkFqcGc@._V1_.jpg',
    'https://es.wikipedia.org/wiki/Mimí_Lazo'
  ),
  (
    'Sheryl Rubio',
    'Actor',
    'Femenino',
    1992,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'TV / Telenovela',
    'https://static.wikia.nocookie.net/house-of-flowers/images/8/85/Sheryl_Rubio.jpg/revision/latest?cb=20191011185234',
    'https://es.wikipedia.org/wiki/Sheryl_Rubio'
  ),
  (
    'María Gabriela de Faría',
    'Actor',
    'Femenino',
    1992,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 2010-actualidad',
    'TV / Cine',
    'https://upload.wikimedia.org/wikipedia/commons/d/de/Mar%C3%ADa_Gabriela_de_Far%C3%ADa_en_2024_01.jpg',
    'https://es.wikipedia.org/wiki/Mar%C3%ADa_Gabriela_de_Far%C3%ADa'
  ),
  (
    'Yanis Chimaras',
    'Actor',
    'Masculino',
    1955,
    'Caracas',
    'Fallecido',
    'Latinoamérica',
    'Década de 1980-2000',
    'TV / Telenovela',
    'https://pics.filmaffinity.com/001229202218656-nm_200.jpg',
    'https://es.wikipedia.org/wiki/Yanis_Chimaras'
  ),
  (
    'Daniel Alvarado',
    'Actor',
    'Masculino',
    1949,
    'Zulia',
    'Fallecido',
    'Local',
    'Década de 1970-2010',
    'TV / Cine / Gaita',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKcc0WWfBksDtpAoImtjl9O_e_lXGoObgHpIzwBJLIpsMODJs2K2TnkOQBsQDTzoGxZzCwiJnQjCiaBdWVTO2CZPGqCGVhPXApp_Ch9W4&s=10',
    'https://es.wikipedia.org/wiki/Daniel_Alvarado'
  ),
  -- ---------------------------------------------------------------- comediantes
  (
    'Laureano Márquez',
    'Comediante',
    'Masculino',
    1963,
    'Islas Canarias (España, criado en Venezuela)',
    'Vivo',
    'Latinoamérica',
    'Década de 1990-actualidad',
    'Stand-up / Sátira Política',
    'https://upload.wikimedia.org/wikipedia/commons/9/9e/Laureano_Marquez_IPFA_winner_2010.JPG',
    'https://es.wikipedia.org/wiki/Laureano_M%C3%A1rquez'
  ),
  (
    'Emilio Lovera',
    'Comediante',
    'Masculino',
    1961,
    'Caracas',
    'Vivo',
    'Local',
    'Década de 1980-2010',
    'Stand-up / TV',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeRL7-WMMNyaIDszXX0wp56KPocYqg-Ip7bCO8kO7Je3HlC0VX4Ch142sb7s-Ymo4LaH-o6rUZ6nFbHAGrPNKiTkZqh7DPR40-TBye1aM&s=10',
    'https://es.wikipedia.org/wiki/Emilio_Lovera'
  ),
  (
    'Benjamín Rausseo ''Er Conde del Guácharo''',
    'Comediante',
    'Masculino',
    1961,
    'Aragua',
    'Vivo',
    'Local',
    'Década de 1980-2000',
    'Stand-up / TV / Character Comedy',
    'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Conde_del_guacharo.jpg/250px-Conde_del_guacharo.jpg',
    'https://es.wikipedia.org/wiki/Benjam%C3%ADn_Rausseo'
  ),
  (
    'Víctor Drija',
    'Comediante',
    'Masculino',
    1980,
    'Caracas',
    'Vivo',
    'Local',
    'Década de 2000-2010',
    'Stand-up / TV',
    'https://yt3.googleusercontent.com/S9CnuEIpEy_lpT77lKW5pMi4crOv7zjc4voprRJQ5uRLRX6aS94Fzuwnm773w9MrYJ9jGLhG14I=s900-c-k-c0x00ffffff-no-rj',
    'https://es.wikipedia.org/wiki/V%C3%ADctor_Drija'
  ),
  -- ------------------------------------------------------------------ escritores
  (
    'Arturo Uslar Pietri',
    'Escritor',
    'Masculino',
    1906,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1930-1990',
    'Novela / Ensayo / Política',
    'https://upload.wikimedia.org/wikipedia/commons/f/f7/Arturo_Uslar_Pietri_El_Nacional_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Arturo_Uslar_Pietri'
  ),
  (
    'Rómulo Gallegos',
    'Escritor',
    'Masculino',
    1884,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1920-1960',
    'Novela / Política',
    'https://upload.wikimedia.org/wikipedia/commons/f/fd/R%C3%B3mulo_Gallegos_1940s.jpg',
    'https://es.wikipedia.org/wiki/R%C3%B3mulo_Gallegos'
  ),
  (
    'Andrés Bello',
    'Escritor',
    'Masculino',
    1781,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1810-1860',
    'Humanista / Educador / Diplomático',
    'https://upload.wikimedia.org/wikipedia/commons/a/a7/Andres_Bello-Quinsac.jpg',
    'https://es.wikipedia.org/wiki/Andr%C3%A9s_Bello'
  ),
  (
    'Simón Rodríguez',
    'Escritor',
    'Masculino',
    1769,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1800-1850',
    'Educador / Filósofo',
    'https://upload.wikimedia.org/wikipedia/commons/4/4a/Anonimo_010.JPG',
    'https://es.wikipedia.org/wiki/Sim%C3%B3n_Rodr%C3%ADguez'
  ),
  (
    'Teresa de la Parra',
    'Escritor',
    'Femenino',
    1889,
    'París (Francia, criada en Venezuela)',
    'Fallecido',
    'Latinoamérica',
    'Década de 1920-1930',
    'Novela (Ifigenia)',
    'https://upload.wikimedia.org/wikipedia/commons/6/69/Teresa_de_la_Parra.jpg',
    'https://es.wikipedia.org/wiki/Teresa_de_la_Parra'
  ),
  (
    'Miguel Otero Silva',
    'Escritor',
    'Masculino',
    1908,
    'Anzoátegui',
    'Fallecido',
    'Latinoamérica',
    'Década de 1930-1980',
    'Novela / Periodismo',
    'https://upload.wikimedia.org/wikipedia/commons/2/24/Otero_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Miguel_Otero_Silva'
  ),
  (
    'Aquiles Nazoa',
    'Escritor',
    'Masculino',
    1920,
    'Caracas',
    'Fallecido',
    'Latinoamérica',
    'Década de 1940-1970',
    'Poesía / Humor',
    'https://upload.wikimedia.org/wikipedia/commons/4/4d/Aquiles_Nazoa.jpg',
    'https://es.wikipedia.org/wiki/Aquiles_Nazoa'
  ),
  -- ---------------------------------------------------------------- periodistas
  (
    'Patricia Poleo',
    'Periodista',
    'Femenino',
    1965,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 1990-2010',
    'Periodismo Político',
    'https://upload.wikimedia.org/wikipedia/commons/9/9b/Patricia_Poleo_en_noviembre_de_2011.png',
    'https://es.wikipedia.org/wiki/Patricia_Poleo'
  ),
  (
    'Nelson Bocaranda',
    'Periodista',
    'Masculino',
    1945,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 1970-2010',
    'Periodismo Político',
    'https://upload.wikimedia.org/wikipedia/commons/d/dc/Nelson_Bocaranda_Sardi.jpg',
    'https://es.wikipedia.org/wiki/Nelson_Bocaranda'
  ),
  (
    'Teodoro Petkoff',
    'Periodista',
    'Masculino',
    1932,
    'Zulia',
    'Fallecido',
    'Latinoamérica',
    'Década de 1960-2010',
    'Política',
    'https://upload.wikimedia.org/wikipedia/commons/f/f0/Teodoro_Petkoff_Senate_of_Poland.jpg',
    'https://es.wikipedia.org/wiki/Teodoro_Petkoff'
  ),
  -- ------------------------------------------------------------ presentadores tv
  (
    'Chiquinquirá Delgado',
    'Presentador de TV',
    'Femenino',
    1972,
    'Zulia',
    'Vivo',
    'Global',
    'Década de 1990-actualidad',
    'Presentador de TV / Modelo',
    'https://upload.wikimedia.org/wikipedia/commons/3/36/Chiquinquir%C3%A1_Delgado_en_Dulce_Osuna.jpg',
    'https://es.wikipedia.org/wiki/Chiquinquir%C3%A1_Delgado'
  ),
  (
    'Daniel Sarcos',
    'Presentador de TV',
    'Masculino',
    1967,
    'Monagas',
    'Vivo',
    'Latinoamérica',
    'Década de 1990-2010',
    'Presentador de TV / Comediante',
    'https://upload.wikimedia.org/wikipedia/commons/a/ab/Daniel_Sarcos.jpg',
    'https://es.wikipedia.org/wiki/Daniel_Sarcos'
  ),
  (
    'Maite Delgado',
    'Presentador de TV',
    'Femenino',
    1967,
    'Caracas',
    'Vivo',
    'Local',
    'Década de 1980-2010',
    'Presentador de TV / Modelo',
    'https://upload.wikimedia.org/wikipedia/commons/b/bc/Maiteenero.jpg',
    'https://es.wikipedia.org/wiki/Maite_Delgado'
  ),
  (
    'Erika de la Vega',
    'Presentador de TV',
    'Femenino',
    1977,
    'Caracas',
    'Vivo',
    'Latinoamérica',
    'Década de 2000-actualidad',
    'Presentación / Comedia',
    'https://upload.wikimedia.org/wikipedia/commons/7/7b/Erika_de_la_Vega_%28cropped%29.jpg',
    'https://es.wikipedia.org/wiki/Erika_de_la_Vega'
  ),
  -- -------------------------------------------------------------------- artistas
  (
    'Carlos Cruz-Díez',
    'Artista',
    'Masculino',
    1923,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1960-2010',
    'Cinetismo / Arte óptico',
    'https://uploads4.wikiart.org/temp/919172d0-e550-460a-8aa4-33da20102e52.jpg',
    'https://es.wikipedia.org/wiki/Carlos_Cruz-Diez'
  ),
  (
    'Jesús Rafael Soto',
    'Artista',
    'Masculino',
    1923,
    'Bolívar',
    'Fallecido',
    'Global',
    'Década de 1950-2000',
    'Arte Cinético',
    'https://upload.wikimedia.org/wikipedia/commons/b/bf/Jesus_Rafael_Soto_by_Lothar_Wolleh.jpg',
    'https://es.wikipedia.org/wiki/Jes%C3%BAs_Rafael_Soto'
  ),
  (
    'Alejandro Otero',
    'Artista',
    'Masculino',
    1921,
    'Bolívar',
    'Fallecido',
    'Global',
    'Década de 1950-1990',
    'Abstraccionismo Geométrico',
    'https://upload.wikimedia.org/wikipedia/commons/f/f7/Alejandro_Otero_en_1960.jpg',
    'https://es.wikipedia.org/wiki/Alejandro_Otero'
  ),
  (
    'Armando Reverón',
    'Artista',
    'Masculino',
    1889,
    'Caracas',
    'Fallecido',
    'Global',
    'Década de 1910-1950',
    'Pintura',
    'https://upload.wikimedia.org/wikipedia/commons/f/ff/A.Reveron.png',
    'https://es.wikipedia.org/wiki/Armando_Reverón'
  ),
  (
    'Arturo Michelena',
    'Artista',
    'Masculino',
    1863,
    'Carabobo',
    'Fallecido',
    'Latinoamérica',
    'Década de 1880-1890',
    'Pintura Clásica',
    'https://upload.wikimedia.org/wikipedia/commons/5/5a/Arturo_Michelena1.jpg',
    'https://es.wikipedia.org/wiki/Arturo_Michelena'
  ),
  (
    'Cristóbal Rojas',
    'Artista',
    'Masculino',
    1858,
    'Miranda',
    'Fallecido',
    'Local',
    'Década de 1880-1910',
    'Realismo',
    'https://upload.wikimedia.org/wikipedia/commons/d/d9/Cristobal_Rojas_40.JPG',
    'https://es.wikipedia.org/wiki/Crist%C3%B3bal_Rojas'
  ),
  (
    'Martín Tovar y Tovar',
    'Artista',
    'Masculino',
    1827,
    'Caracas',
    'Fallecido',
    'Local',
    'Década de 1870-1900',
    'Pintura Histórica',
    'https://upload.wikimedia.org/wikipedia/commons/3/36/Antonio_Herrera_Toro_1878_000.jpg',
    'https://es.wikipedia.org/wiki/Mart%C3%ADn_Tovar_y_Tovar'
  ),
  (
    'Carolina Herrera',
    'Artista',
    'Femenino',
    1939,
    'Caracas',
    'Vivo',
    'Global',
    'Década de 1980-actualidad',
    'Moda / Alta Costura',
    'https://upload.wikimedia.org/wikipedia/commons/d/d5/Carolina_Herrera_alt.jpg',
    'https://es.wikipedia.org/wiki/Carolina_Herrera'
  );

-- Explicit ids were inserted, so resync the SERIAL sequence past them.
SELECT
  setval(
    'characters_id_seq',
    (
      SELECT
        MAX(id)
      FROM
        characters
    )
  );
