-- Venedle: initial schema + seed for the characters table.
-- Mounted into /docker-entrypoint-initdb.d/ by compose; runs only when the
-- Postgres data volume is empty (first boot).
-- Individuals only (no bands/duos). Foreign-born figures who built their
-- careers in Venezuela are kept with their origin noted verbatim.

CREATE TABLE characters (
  id                  SERIAL PRIMARY KEY,
  name                VARCHAR(255) NOT NULL UNIQUE,
  field               VARCHAR(50)  NOT NULL,
  gender              VARCHAR(20)  NOT NULL,
  birth_year          INTEGER      NOT NULL,
  state_of_origin     VARCHAR(100) NOT NULL,
  status              VARCHAR(20)  NOT NULL,
  international_reach VARCHAR(30)  NOT NULL,
  peak_era            VARCHAR(100) NOT NULL,
  discipline_genre    VARCHAR(150) NOT NULL,
  image_url           TEXT,

  CONSTRAINT characters_field_check
    CHECK (field IN ('Político', 'Deportista', 'Músico', 'Actor',
                     'Comediante', 'Periodista', 'Presentador de TV',
                     'Escritor', 'Artista')),
  CONSTRAINT characters_gender_check
    CHECK (gender IN ('Masculino', 'Femenino', 'Non-binario')),
  CONSTRAINT characters_status_check
    CHECK (status IN ('Vivo', 'Fallecido')),
  CONSTRAINT characters_international_reach_check
    CHECK (international_reach IN ('Local', 'Latinoamérica', 'Global'))
);

INSERT INTO characters
  (id, name, field, gender, birth_year, state_of_origin, status,
   international_reach, peak_era, discipline_genre, image_url)
VALUES
  -- ---------------------------------------------------------------- políticos
  (1, 'Hugo Chávez', 'Político', 'Masculino', 1954, 'Barinas', 'Fallecido',
   'Global', 'Década de 1990-2000', 'Presidente / Militar',
   'https://upload.wikimedia.org/wikipedia/commons/3/3f/Hugo_Ch%C3%A1vez_military.png'),
  (2, 'Nicolás Maduro', 'Político', 'Masculino', 1962, 'Caracas', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Presidente',
   'https://upload.wikimedia.org/wikipedia/commons/7/7e/Nicol%C3%A1s_Maduro_2023_%28cropped%29.jpg'),
  (3, 'Simón Bolívar', 'Político', 'Masculino', 1783, 'Caracas', 'Fallecido',
   'Global', 'Década de 1810-1820', 'Libertador',
   'https://upload.wikimedia.org/wikipedia/commons/0/0f/Sim%C3%B3n_Bol%C3%ADvar_%28Tovar%29.jpg'),
  (4, 'Henrique Capriles', 'Político', 'Masculino', 1972, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 2000-2010', 'Gobernador / Candidato Presidencial',
   'https://upload.wikimedia.org/wikipedia/commons/5/5e/Henrique_Capriles_Radonski.jpg'),
  (5, 'Leopoldo López', 'Político', 'Masculino', 1971, 'Caracas', 'Vivo',
   'Global', 'Década de 2000-2010', 'Líder de la Oposición',
   'https://upload.wikimedia.org/wikipedia/commons/3/3e/Leopoldo_L%C3%B3pez_2015.jpg'),
  (6, 'Juan Guaidó', 'Político', 'Masculino', 1983, 'Vargas', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Líder de la Oposición / Presidente Interino',
   'https://upload.wikimedia.org/wikipedia/commons/8/8e/Juan_Guaid%C3%B3_%282019%29.jpg'),
  (7, 'Rafael Caldera', 'Político', 'Masculino', 1916, 'Yaracuy', 'Fallecido',
   'Latinoamérica', 'Década de 1960-1990', 'Presidente',
   'https://upload.wikimedia.org/wikipedia/commons/9/92/1994._Febrero%2C_7._Rafael_Caldera_en_su_segunda_presidencia.jpg'),
  (8, 'Rómulo Betancourt', 'Político', 'Masculino', 1908, 'Miranda', 'Fallecido',
   'Latinoamérica', 'Década de 1940-1960', 'Presidente / Fundador de AD',
   'https://upload.wikimedia.org/wikipedia/commons/d/df/Foto_oficial_R%C3%B3mulo_Betancourt_1959.jpg'),
  (80, 'Francisco de Miranda', 'Político', 'Masculino', 1750, 'Caracas', 'Fallecido',
   'Global', 'Década de 1780-1810', 'Precursor / Militar', NULL),
  (81, 'Antonio José de Sucre', 'Político', 'Masculino', 1795, 'Sucre', 'Fallecido',
   'Global', 'Década de 1820', 'Gran Mariscal de Ayacucho', NULL),
  (82, 'Carlos Andrés Pérez', 'Político', 'Masculino', 1922, 'Táchira', 'Fallecido',
   'Global', 'Década de 1970-1990', 'Presidente', NULL),
  (83, 'Marcos Pérez Jiménez', 'Político', 'Masculino', 1914, 'Táchira', 'Fallecido',
   'Global', 'Década de 1950', 'Dictador / Militar', NULL),
  (84, 'Juan Vicente Gómez', 'Político', 'Masculino', 1857, 'Táchira', 'Fallecido',
   'Global', 'Década de 1900-1930', 'Dictador / Militar', NULL),
  (85, 'María Corina Machado', 'Político', 'Femenino', 1967, 'Caracas', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Líder de la Oposición', NULL),
  (86, 'Diosdado Cabello', 'Político', 'Masculino', 1963, 'Monagas', 'Vivo',
   'Global', 'Década de 2000-actualidad', 'Militar / Dirigente Político', NULL),
  (87, 'Jóvito Villalba', 'Político', 'Masculino', 1908, 'Nueva Esparta', 'Fallecido',
   'Latinoamérica', 'Década de 1940-1970', 'Fundador de URD', NULL),
  (88, 'Andrés Eloy Blanco', 'Político', 'Masculino', 1896, 'Sucre', 'Fallecido',
   'Global', 'Década de 1920-1950', 'Poeta / Político', NULL),
  (89, 'Ezequiel Zamora', 'Político', 'Masculino', 1817, 'Miranda', 'Fallecido',
   'Local', 'Década de 1840-1860', 'General del Pueblo Soberano', NULL),
  (90, 'Antonio Guzmán Blanco', 'Político', 'Masculino', 1829, 'Caracas', 'Fallecido',
   'Latinoamérica', 'Década de 1870-1880', 'Presidente / Modernizador', NULL),
  (91, 'Rafael Urdaneta', 'Político', 'Masculino', 1788, 'Zulia', 'Fallecido',
   'Global', 'Década de 1810-1830', 'Militar / Prócer', NULL),
  (92, 'José Antonio Páez', 'Político', 'Masculino', 1790, 'Portuguesa', 'Fallecido',
   'Latinoamérica', 'Década de 1830-1850', 'Caudillo / Presidente', NULL),
  (93, 'Isaías Medina Angarita', 'Político', 'Masculino', 1897, 'Táchira', 'Fallecido',
   'Latinoamérica', 'Década de 1940', 'Presidente / Militar', NULL),
  -- --------------------------------------------------------------- deportistas
  (9, 'Miguel Cabrera', 'Deportista', 'Masculino', 1983, 'Aragua', 'Vivo',
   'Global', 'Década de 2000-2010', 'Béisbol',
   'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Miguel_Cabrera_in_2014_%2814174921525%29.jpg/960px-Miguel_Cabrera_in_2014_%2814174921525%29.jpg'),
  (10, 'Omar Vizquel', 'Deportista', 'Masculino', 1967, 'Caracas', 'Vivo',
   'Global', 'Década de 1990-2000', 'Béisbol',
   'https://upload.wikimedia.org/wikipedia/commons/7/7e/Omar_Vizquel_2011.jpg'),
  (11, 'Yulimar Rojas', 'Deportista', 'Femenino', 1995, 'Anzoátegui', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Atletismo (Salto Triple)',
   'https://upload.wikimedia.org/wikipedia/commons/9/9e/Yulimar_Rojas_2019.jpg'),
  (12, 'Pastor Maldonado', 'Deportista', 'Masculino', 1985, 'Zulia', 'Vivo',
   'Global', 'Década de 2010', 'Fórmula 1',
   'https://upload.wikimedia.org/wikipedia/commons/4/4e/Pastor_Maldonado_2015.jpg'),
  (13, 'Magglio Ordóñez', 'Deportista', 'Masculino', 1974, 'Caracas', 'Vivo',
   'Global', 'Década de 1990-2000', 'Béisbol',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Magglio_Ord%C3%B3%C3%B1ez_2012.jpg'),
  (14, 'Johan Santana', 'Deportista', 'Masculino', 1979, 'Mérida', 'Vivo',
   'Global', 'Década de 2000-2010', 'Béisbol',
   'https://upload.wikimedia.org/wikipedia/commons/8/8e/Johan_Santana_2008.jpg'),
  (15, 'Félix Hernández', 'Deportista', 'Masculino', 1986, 'Carabobo', 'Vivo',
   'Global', 'Década de 2000-2010', 'Béisbol',
   'https://upload.wikimedia.org/wikipedia/commons/7/7e/F%C3%A9lix_Hern%C3%A1ndez_2015.jpg'),
  (16, 'Roberto Cavallo', 'Deportista', 'Masculino', 1940, 'Caracas', 'Vivo',
   'Global', 'Década de 1960-1970', 'Boxeo', NULL),
  (17, 'Edwin Valero', 'Deportista', 'Masculino', 1981, 'Mérida', 'Fallecido',
   'Global', 'Década de 2000', 'Boxeo',
   'https://upload.wikimedia.org/wikipedia/commons/3/3e/Edwin_Valero.jpg'),
  (18, 'Gabriela Isler', 'Deportista', 'Femenino', 1988, 'Carabobo', 'Vivo',
   'Global', 'Década de 2010', 'Reinado de Belleza (Miss Universo)',
   'https://upload.wikimedia.org/wikipedia/commons/8/8e/Gabriela_Isler_2013.jpg'),
  (19, 'Dayana Mendoza', 'Deportista', 'Femenino', 1986, 'Caracas', 'Vivo',
   'Global', 'Década de 2000', 'Reinado de Belleza (Miss Universo)',
   'https://upload.wikimedia.org/wikipedia/commons/7/7e/Dayana_Mendoza_2008.jpg'),
  (20, 'Stefanía Fernández', 'Deportista', 'Femenino', 1990, 'Mérida', 'Vivo',
   'Global', 'Década de 2000-2010', 'Reinado de Belleza (Miss Universo)',
   'https://upload.wikimedia.org/wikipedia/commons/9/9e/Stefan%C3%ADa_Fern%C3%A1ndez_2009.jpg'),
  (21, 'Irene Sáez', 'Deportista', 'Femenino', 1961, 'Caracas', 'Vivo',
   'Global', 'Década de 1980-1990', 'Reinado de Belleza (Miss Universo) / Política',
   'https://upload.wikimedia.org/wikipedia/commons/4/4e/Irene_S%C3%A1ez.jpg'),
  (59, 'Salomón Rondón', 'Deportista', 'Masculino', 1989, 'Caracas', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Fútbol', NULL),
  (60, 'Josef Martínez', 'Deportista', 'Masculino', 1993, 'Carabobo', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Fútbol', NULL),
  (61, 'Juan Arango', 'Deportista', 'Masculino', 1980, 'Zulia', 'Vivo',
   'Latinoamérica', 'Década de 2000-2010', 'Fútbol', NULL),
  (62, 'Tomás Rincón', 'Deportista', 'Masculino', 1988, 'Táchira', 'Vivo',
   'Latinoamérica', 'Década de 2010-actualidad', 'Fútbol', NULL),
  (63, 'Yeferson Soteldo', 'Deportista', 'Masculino', 1997, 'Portuguesa', 'Vivo',
   'Latinoamérica', 'Década de 2020-actualidad', 'Fútbol', NULL),
  (64, 'Luis Aparicio', 'Deportista', 'Masculino', 1934, 'Zulia', 'Vivo',
   'Global', 'Década de 1950-1970', 'Béisbol', NULL),
  (65, 'José Altuve', 'Deportista', 'Masculino', 1990, 'Carabobo', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Béisbol', NULL),
  (66, 'Ronald Acuña Jr.', 'Deportista', 'Masculino', 1997, 'Vargas', 'Vivo',
   'Global', 'Década de 2020-actualidad', 'Béisbol', NULL),
  (67, 'Salvador Pérez', 'Deportista', 'Masculino', 1990, 'Carabobo', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Béisbol', NULL),
  (68, 'Andrés Galarraga', 'Deportista', 'Masculino', 1961, 'Caracas', 'Vivo',
   'Global', 'Década de 1980-2000', 'Béisbol', NULL),
  (69, 'Bobby Abreu', 'Deportista', 'Masculino', 1974, 'Aragua', 'Vivo',
   'Global', 'Década de 1990-2010', 'Béisbol', NULL),
  (70, 'Dave Concepción', 'Deportista', 'Masculino', 1948, 'Miranda', 'Vivo',
   'Global', 'Década de 1970-1980', 'Béisbol', NULL),
  (71, 'Oswaldo Guillén', 'Deportista', 'Masculino', 1964, 'Miranda', 'Vivo',
   'Global', 'Década de 1980-2000', 'Béisbol', NULL),
  (72, 'César Tovar', 'Deportista', 'Masculino', 1940, 'Caracas', 'Fallecido',
   'Global', 'Década de 1960-1970', 'Béisbol', NULL),
  (73, 'Carlos Zambrano', 'Deportista', 'Masculino', 1981, 'Carabobo', 'Vivo',
   'Global', 'Década de 2000-2010', 'Béisbol', NULL),
  (74, 'Francisco Rodríguez', 'Deportista', 'Masculino', 1982, 'Caracas', 'Vivo',
   'Global', 'Década de 2000-2010', 'Béisbol', NULL),
  (75, 'Eugenio Suárez', 'Deportista', 'Masculino', 1991, 'Bolívar', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Béisbol', NULL),
  (76, 'Rubén Limardo', 'Deportista', 'Masculino', 1985, 'Bolívar', 'Vivo',
   'Global', 'Década de 2010', 'Esgrima', NULL),
  (77, 'Johnny Cecotto', 'Deportista', 'Masculino', 1956, 'Caracas', 'Vivo',
   'Global', 'Década de 1970-1980', 'Motociclismo', NULL),
  (78, 'Greivis Vásquez', 'Deportista', 'Masculino', 1987, 'Caracas', 'Vivo',
   'Global', 'Década de 2010', 'Baloncesto', NULL),
  (79, 'Daniel Dhers', 'Deportista', 'Masculino', 1985, 'Caracas', 'Vivo',
   'Global', 'Década de 2000-2020', 'BMX', NULL),
  -- -------------------------------------------------------------------- músicos
  (22, 'José Luis Rodríguez ''El Puma''', 'Músico', 'Masculino', 1943, 'Caracas', 'Vivo',
   'Global', 'Década de 1970-1990', 'Pop / Balada',
   'https://upload.wikimedia.org/wikipedia/commons/5/5e/Jos%C3%A9_Luis_Rodr%C3%ADguez_%27El_Puma%27.jpg'),
  (23, 'Ricardo Montaner', 'Músico', 'Masculino', 1957, 'Valencia (Carabobo)', 'Vivo',
   'Global', 'Década de 1980-actualidad', 'Pop / Balada',
   'https://upload.wikimedia.org/wikipedia/commons/5/5e/Ricardo_Montaner_2019.jpg'),
  (24, 'Franco De Vita', 'Músico', 'Masculino', 1954, 'Caracas', 'Vivo',
   'Global', 'Década de 1980-2010', 'Pop / Rock',
   'https://upload.wikimedia.org/wikipedia/commons/5/5e/Franco_De_Vita.jpg'),
  (25, 'Carlos Baute', 'Músico', 'Masculino', 1974, 'Caracas', 'Vivo',
   'Global', 'Década de 2000-2010', 'Pop / Pop Latino',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Carlos_Baute.jpg'),
  (27, 'Oscar D''León', 'Músico', 'Masculino', 1943, 'Caracas', 'Vivo',
   'Global', 'Década de 1970-2000', 'Salsa',
   'https://upload.wikimedia.org/wikipedia/commons/5/5e/Oscar_D%27Le%C3%B3n.jpg'),
  (32, 'Luis Silva', 'Músico', 'Masculino', 1969, 'Caracas', 'Vivo',
   'Local', 'Década de 1990-2010', 'Pop / Balada', NULL),
  (33, 'Simón Díaz', 'Músico', 'Masculino', 1928, 'Aragua', 'Fallecido',
   'Global', 'Década de 1960-2000', 'Folk / Llanera',
   'https://upload.wikimedia.org/wikipedia/commons/5/5e/Sim%C3%B3n_D%C3%ADaz.jpg'),
  (34, 'Soledad Bravo', 'Músico', 'Femenino', 1943, 'Logroño (España, criado en Venezuela)', 'Vivo',
   'Latinoamérica', 'Década de 1960-1990', 'Folk / Protesta',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Soledad_Bravo.jpg'),
  (36, 'Reymar Perdomo', 'Músico', 'Femenino', 1992, 'Zulia', 'Vivo',
   'Latinoamérica', 'Década de 2010-actualidad', 'Folk / Llanera', NULL),
  (52, 'Teresa Carreño', 'Músico', 'Femenino', 1853, 'Caracas', 'Fallecido',
   'Global', 'Década de 1860-1910', 'Piano Clásico / Compositora',
   'https://upload.wikimedia.org/wikipedia/commons/5/5e/Teresa_Carre%C3%B1o.jpg'),
  (94, 'Neutro Shorty', 'Músico', 'Masculino', 1994, 'Caracas', 'Vivo',
   'Global', 'Década de 2020-actualidad', 'Trap / Rap', NULL),
  (95, 'Danny Ocean', 'Músico', 'Masculino', 1992, 'Caracas', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Pop Urbano', NULL),
  (96, 'Big Soto', 'Músico', 'Masculino', 1996, 'Sucre', 'Vivo',
   'Global', 'Década de 2020-actualidad', 'Trap / Rap', NULL),
  (97, 'Nacho', 'Músico', 'Masculino', 1983, 'Anzoátegui', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'Reggaetón / Pop', NULL),
  (98, 'Canserbero', 'Músico', 'Masculino', 1988, 'Aragua', 'Fallecido',
   'Global', 'Década de 2010', 'Rap / Hip Hop', NULL),
  (99, 'Gustavo Dudamel', 'Músico', 'Masculino', 1981, 'Lara', 'Vivo',
   'Global', 'Década de 2000-actualidad', 'Director de Orquesta', NULL),
  (100, 'José Antonio Abreu', 'Músico', 'Masculino', 1939, 'Trujillo', 'Fallecido',
   'Global', 'Década de 1970-2010', 'Fundador de El Sistema / Educador Musical', NULL),
  (101, 'Alfredo Sadel', 'Músico', 'Masculino', 1930, 'Caracas', 'Fallecido',
   'Global', 'Década de 1940-1980', 'Bolero / Lírico', NULL),
  (102, 'Aldemaro Romero', 'Músico', 'Masculino', 1928, 'Carabobo', 'Fallecido',
   'Global', 'Década de 1950-2000', 'Música Popular / Orquestas', NULL),
  (103, 'Reynaldo Armas', 'Músico', 'Masculino', 1953, 'Guárico', 'Vivo',
   'Latinoamérica', 'Década de 1970-actualidad', 'Música Llanera', NULL),
  (104, 'Ilan Chester', 'Músico', 'Masculino', 1952, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 1980-actualidad', 'Pop / Balada', NULL),
  (105, 'Gualberto Ibarreto', 'Músico', 'Masculino', 1947, 'Sucre', 'Vivo',
   'Latinoamérica', 'Década de 1970-actualidad', 'Folclore / Galerón', NULL),
  (106, 'Cecilia Todd', 'Músico', 'Femenino', 1954, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 1970-actualidad', 'Folclore', NULL),
  -- --------------------------------------------------------------------- actores
  (37, 'Edgar Ramírez', 'Actor', 'Masculino', 1977, 'Táchira', 'Vivo',
   'Global', 'Década de 2000-actualidad', 'Cine / TV',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Edgar_Ram%C3%ADrez_2017.jpg'),
  (39, 'Majandra Delfino', 'Actor', 'Femenino', 1981, 'Caracas', 'Vivo',
   'Global', 'Década de 1990-2000', 'TV / Cine',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Majandra_Delfino.jpg'),
  (40, 'Jonathan Jakubowicz', 'Actor', 'Masculino', 1978, 'Caracas', 'Vivo',
   'Global', 'Década de 2000-actualidad', 'Cine / Director', NULL),
  (41, 'Gaby Espino', 'Actor', 'Femenino', 1977, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 2000-actualidad', 'TV / Telenovela',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Gaby_Espino.jpg'),
  (42, 'Fernando Carrillo', 'Actor', 'Masculino', 1970, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 1990-2000', 'TV / Telenovela',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Fernando_Carrillo.jpg'),
  (43, 'Lupita Ferrer', 'Actor', 'Femenino', 1947, 'Zulia', 'Vivo',
   'Latinoamérica', 'Década de 1970-1990', 'TV / Telenovela',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Lupita_Ferrer.jpg'),
  (44, 'Hilda Abrahamz', 'Actor', 'Femenino', 1959, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 1980-2000', 'TV / Telenovela',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Hilda_Abrahamz.jpg'),
  (107, 'Mimí Lazo', 'Actor', 'Femenino', 1954, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 1980-actualidad', 'Teatro / TV / Cine', NULL),
  (108, 'Sheryl Rubio', 'Actor', 'Femenino', 1992, 'Caracas', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'TV / Telenovela', NULL),
  (109, 'María Gabriela de Faría', 'Actor', 'Femenino', 1992, 'Caracas', 'Vivo',
   'Global', 'Década de 2010-actualidad', 'TV / Cine', NULL),
  (110, 'Yanis Chimaras', 'Actor', 'Masculino', 1955, 'Caracas', 'Fallecido',
   'Latinoamérica', 'Década de 1980-2000', 'TV / Telenovela', NULL),
  (111, 'Daniel Alvarado', 'Actor', 'Masculino', 1949, 'Zulia', 'Fallecido',
   'Local', 'Década de 1970-2010', 'TV / Cine / Gaita', NULL),
  -- ---------------------------------------------------------------- comediantes
  (45, 'Laureano Márquez', 'Comediante', 'Masculino', 1963, 'Canary Islands (España, criado en Venezuela)', 'Vivo',
   'Latinoamérica', 'Década de 1990-actualidad', 'Stand-up / Sátira Política', NULL),
  (46, 'Emilio Lovera', 'Comediante', 'Masculino', 1961, 'Caracas', 'Vivo',
   'Local', 'Década de 1980-2010', 'Stand-up / TV', NULL),
  (47, 'George Harris', 'Comediante', 'Masculino', 1965, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 2000-actualidad', 'Stand-up / Sátira Política', NULL),
  (48, 'Benjamín Rausseo ''Er Conde del Guácharo''', 'Comediante', 'Masculino', 1961, 'Aragua', 'Vivo',
   'Local', 'Década de 1980-2000', 'Stand-up / TV / Character Comedy', NULL),
  (49, 'Víctor Drija', 'Comediante', 'Masculino', 1980, 'Caracas', 'Vivo',
   'Local', 'Década de 2000-2010', 'Stand-up / TV', NULL),
  -- ------------------------------------------------------------------ escritores
  (50, 'Arturo Uslar Pietri', 'Escritor', 'Masculino', 1906, 'Caracas', 'Fallecido',
   'Global', 'Década de 1930-1990', 'Novela / Ensayo / Política',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Arturo_Uslar_Pietri.jpg'),
  (51, 'Rómulo Gallegos', 'Escritor', 'Masculino', 1884, 'Caracas', 'Fallecido',
   'Global', 'Década de 1920-1960', 'Novela / Política',
   'https://upload.wikimedia.org/wikipedia/commons/5/5e/R%C3%B3mulo_Gallegos.jpg'),
  (112, 'Andrés Bello', 'Escritor', 'Masculino', 1781, 'Caracas', 'Fallecido',
   'Global', 'Década de 1810-1860', 'Humanista / Gramático', NULL),
  (113, 'Simón Rodríguez', 'Escritor', 'Masculino', 1769, 'Caracas', 'Fallecido',
   'Global', 'Década de 1800-1850', 'Educador / Filósofo', NULL),
  (114, 'Teresa de la Parra', 'Escritor', 'Femenino', 1889, 'París (Francia, criada en Venezuela)', 'Fallecido',
   'Latinoamérica', 'Década de 1920-1930', 'Novela (Ifigenia)', NULL),
  (115, 'Miguel Otero Silva', 'Escritor', 'Masculino', 1908, 'Anzoátegui', 'Fallecido',
   'Latinoamérica', 'Década de 1930-1980', 'Novela / Periodismo', NULL),
  (116, 'Aquiles Nazoa', 'Escritor', 'Masculino', 1920, 'Caracas', 'Fallecido',
   'Latinoamérica', 'Década de 1940-1970', 'Poesía / Humor', NULL),
  -- ---------------------------------------------------------------- periodistas
  (53, 'Patricia Poleo', 'Periodista', 'Femenino', 1965, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 1990-2010', 'Periodismo Político', NULL),
  (54, 'Nelson Bocaranda', 'Periodista', 'Masculino', 1945, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 1970-2010', 'Periodismo Político', NULL),
  (55, 'Teodoro Petkoff', 'Periodista', 'Masculino', 1932, 'Zulia', 'Fallecido',
   'Latinoamérica', 'Década de 1960-2010', 'Political Journalism / Politics',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Teodoro_Petkoff.jpg'),
  -- ------------------------------------------------------------ presentadores tv
  (56, 'Chiquinquirá Delgado', 'Presentador de TV', 'Femenino', 1972, 'Zulia', 'Vivo',
   'Global', 'Década de 1990-actualidad', 'Presentador de TV / Modelo',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Chiquinquir%C3%A1_Delgado.jpg'),
  (57, 'Daniel Sarcos', 'Presentador de TV', 'Masculino', 1967, 'Monagas', 'Vivo',
   'Latinoamérica', 'Década de 1990-2010', 'Presentador de TV / Comediante', NULL),
  (58, 'Maite Delgado', 'Presentador de TV', 'Femenino', 1967, 'Caracas', 'Vivo',
   'Local', 'Década de 1980-2010', 'Presentador de TV / Modelo',
   'https://upload.wikimedia.org/wikipedia/commons/6/6e/Maite_Delgado.jpg'),
  (125, 'Erika de la Vega', 'Presentador de TV', 'Femenino', 1977, 'Caracas', 'Vivo',
   'Latinoamérica', 'Década de 2000-actualidad', 'Presentación / Comedia', NULL),
  -- -------------------------------------------------------------------- artistas
  (117, 'Carlos Cruz-Díez', 'Artista', 'Masculino', 1923, 'Caracas', 'Fallecido',
   'Global', 'Década de 1960-2010', 'Cinetismo / Op Art', NULL),
  (118, 'Jesús Rafael Soto', 'Artista', 'Masculino', 1923, 'Bolívar', 'Fallecido',
   'Global', 'Década de 1950-2000', 'Arte Cinético', NULL),
  (119, 'Alejandro Otero', 'Artista', 'Masculino', 1921, 'Bolívar', 'Fallecido',
   'Global', 'Década de 1950-1990', 'Abstraccionismo Geométrico', NULL),
  (120, 'Armando Reverón', 'Artista', 'Masculino', 1889, 'Caracas', 'Fallecido',
   'Global', 'Década de 1910-1950', 'Pintura (Maestro de la Luz)', NULL),
  (121, 'Arturo Michelena', 'Artista', 'Masculino', 1863, 'Carabobo', 'Fallecido',
   'Latinoamérica', 'Década de 1880-1890', 'Pintura Clásica', NULL),
  (122, 'Cristóbal Rojas', 'Artista', 'Masculino', 1858, 'Miranda', 'Fallecido',
   'Local', 'Década de 1880-1910', 'Realismo', NULL),
  (123, 'Martín Tovar y Tovar', 'Artista', 'Masculino', 1827, 'Caracas', 'Fallecido',
   'Local', 'Década de 1870-1900', 'Pintura Histórica', NULL),
  (124, 'Carolina Herrera', 'Artista', 'Femenino', 1939, 'Caracas', 'Vivo',
   'Global', 'Década de 1980-actualidad', 'Moda / Alta Costura', NULL);

-- Explicit ids were inserted, so resync the SERIAL sequence past them.
SELECT setval('characters_id_seq', (SELECT MAX(id) FROM characters));
